// <copyright file="SearchErrorException.cs" company="APIMatic">
// PaypalServerSdk.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using PaypalServerSdk.Standard.Http.Client;
using System.Collections.Generic;

namespace PaypalServerSdk.Standard.Exceptions
{
    /// <summary>
    /// SearchErrorException.
    /// </summary>
    public class SearchErrorException : ApiException
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SearchErrorException"/> class.
        /// </summary>
        /// <param name="reason"> The reason for throwing exception.</param>
        /// <param name="context"> The HTTP context that encapsulates request and response objects.</param>
        public SearchErrorException(string reason, HttpContext context)
            : base(reason, context)
        {
        }

        /// <summary>
        /// The human-readable, unique name of the error.
        /// </summary>
        [JsonProperty("name")]
        public string Name { get; set; }

        /// <summary>
        /// The message that describes the error.
        /// </summary>
        [JsonProperty("message")]
        public new string Message { get; set; }

        /// <summary>
        /// The PayPal internal ID. Used for correlation purposes.
        /// </summary>
        [JsonProperty("debug_id")]
        public string DebugId { get; set; }

        /// <summary>
        /// The information link, or URI, that shows detailed information about this error for the developer.
        /// </summary>
        [JsonProperty("information_link", NullValueHandling = NullValueHandling.Ignore)]
        public string InformationLink { get; set; }

        /// <summary>
        /// An array of additional details about the error.
        /// </summary>
        [JsonProperty("details", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.TransactionSearchErrorDetails> Details { get; set; }

        /// <summary>
        /// An array of request-related [HATEOAS links](/docs/api/reference/api-responses/#hateoas-links).
        /// </summary>
        [JsonProperty("links", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.LinkDescription> Links { get; set; }

        /// <summary>
        /// The total number of transactions. Valid only for `RESULTSET_TOO_LARGE`.
        /// </summary>
        [JsonProperty("total_items", NullValueHandling = NullValueHandling.Ignore)]
        public int? TotalItems { get; set; }

        /// <summary>
        /// The maximum number of transactions. Valid only for `RESULTSET_TOO_LARGE`.
        /// </summary>
        [JsonProperty("maximum_items", NullValueHandling = NullValueHandling.Ignore)]
        public int? MaximumItems { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"SearchErrorException : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected new void ToString(List<string> toStringOutput)
        {
            base.ToString(toStringOutput);
            toStringOutput.Add($"Name = {this.Name ?? "null"}");
            toStringOutput.Add($"Message = {this.Message ?? "null"}");
            toStringOutput.Add($"DebugId = {this.DebugId ?? "null"}");
            toStringOutput.Add($"InformationLink = {this.InformationLink ?? "null"}");
            toStringOutput.Add($"Details = {(this.Details == null ? "null" : $"[{string.Join(", ", this.Details)} ]")}");
            toStringOutput.Add($"Links = {(this.Links == null ? "null" : $"[{string.Join(", ", this.Links)} ]")}");
            toStringOutput.Add($"TotalItems = {(this.TotalItems == null ? "null" : this.TotalItems.ToString())}");
            toStringOutput.Add($"MaximumItems = {(this.MaximumItems == null ? "null" : this.MaximumItems.ToString())}");
            toStringOutput.Add($"StackTrace = {(StackTrace != null ? $"\n{StackTrace}" : "null")}");
        }
    }
}