// <copyright file="AuthorizationIncompleteReason.cs" company="APIMatic">
// PaypalServerSdk.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace PaypalServerSdk.Standard.Models
{
    /// <summary>
    /// AuthorizationIncompleteReason.
    /// </summary>

    [JsonConverter(typeof(UnknownEnumConverter<StringEnumConverter>), nameof(_Unknown))]
    public enum AuthorizationIncompleteReason
    {
        /// <summary>
        ///Authorization is pending manual review.
        /// PendingReview.
        /// </summary>
        [EnumMember(Value = "PENDING_REVIEW")]
        PendingReview,

        /// <summary>
        ///Risk Filter set by the payee failed for the transaction.
        /// DeclinedByRiskFraudFilters.
        /// </summary>
        [EnumMember(Value = "DECLINED_BY_RISK_FRAUD_FILTERS")]
        DeclinedByRiskFraudFilters,

        /// <summary>
        /// Unknown values will be mapped by this enum member.
        /// </summary>
        _Unknown
    }
}