// <copyright file="BalancesResponse.cs" company="APIMatic">
// PaypalServerSdk.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using PaypalServerSdk.Standard;
using PaypalServerSdk.Standard.Utilities;

namespace PaypalServerSdk.Standard.Models
{
    /// <summary>
    /// BalancesResponse.
    /// </summary>
    public class BalancesResponse
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BalancesResponse"/> class.
        /// </summary>
        public BalancesResponse()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="BalancesResponse"/> class.
        /// </summary>
        /// <param name="balances">balances.</param>
        /// <param name="accountId">account_id.</param>
        /// <param name="asOfTime">as_of_time.</param>
        /// <param name="lastRefreshTime">last_refresh_time.</param>
        public BalancesResponse(
            List<Models.BalanceInformation> balances = null,
            string accountId = null,
            string asOfTime = null,
            string lastRefreshTime = null)
        {
            this.Balances = balances;
            this.AccountId = accountId;
            this.AsOfTime = asOfTime;
            this.LastRefreshTime = lastRefreshTime;
        }

        /// <summary>
        /// An array of balance detail objects.
        /// </summary>
        [JsonProperty("balances", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.BalanceInformation> Balances { get; set; }

        /// <summary>
        /// The PayPal payer ID, which is a masked version of the PayPal account number intended for use with third parties. The account number is reversibly encrypted and a proprietary variant of Base32 is used to encode the result.
        /// </summary>
        [JsonProperty("account_id", NullValueHandling = NullValueHandling.Ignore)]
        public string AccountId { get; set; }

        /// <summary>
        /// The date and time, in [Internet date and time format](https://tools.ietf.org/html/rfc3339#section-5.6). Seconds are required while fractional seconds are optional. Note: The regular expression provides guidance but does not reject all invalid dates.
        /// </summary>
        [JsonProperty("as_of_time", NullValueHandling = NullValueHandling.Ignore)]
        public string AsOfTime { get; set; }

        /// <summary>
        /// The date and time, in [Internet date and time format](https://tools.ietf.org/html/rfc3339#section-5.6). Seconds are required while fractional seconds are optional. Note: The regular expression provides guidance but does not reject all invalid dates.
        /// </summary>
        [JsonProperty("last_refresh_time", NullValueHandling = NullValueHandling.Ignore)]
        public string LastRefreshTime { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"BalancesResponse : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is BalancesResponse other &&
                (this.Balances == null && other.Balances == null ||
                 this.Balances?.Equals(other.Balances) == true) &&
                (this.AccountId == null && other.AccountId == null ||
                 this.AccountId?.Equals(other.AccountId) == true) &&
                (this.AsOfTime == null && other.AsOfTime == null ||
                 this.AsOfTime?.Equals(other.AsOfTime) == true) &&
                (this.LastRefreshTime == null && other.LastRefreshTime == null ||
                 this.LastRefreshTime?.Equals(other.LastRefreshTime) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Balances = {(this.Balances == null ? "null" : $"[{string.Join(", ", this.Balances)} ]")}");
            toStringOutput.Add($"AccountId = {this.AccountId ?? "null"}");
            toStringOutput.Add($"AsOfTime = {this.AsOfTime ?? "null"}");
            toStringOutput.Add($"LastRefreshTime = {this.LastRefreshTime ?? "null"}");
        }
    }
}