// <copyright file="BankRequest.cs" company="APIMatic">
// PaypalServerSdk.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using PaypalServerSdk.Standard.Utilities;
using System.Collections.Generic;

namespace PaypalServerSdk.Standard.Models
{
    /// <summary>
    /// BankRequest.
    /// </summary>
    public class BankRequest
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BankRequest"/> class.
        /// </summary>
        public BankRequest()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="BankRequest"/> class.
        /// </summary>
        /// <param name="achDebit">ach_debit.</param>
        /// <param name="sepaDebit">sepa_debit.</param>
        public BankRequest(
            JsonValue achDebit = null,
            Models.SepaDebitRequest sepaDebit = null)
        {
            this.AchDebit = achDebit;
            this.SepaDebit = sepaDebit;
        }

        /// <summary>
        /// A Resource representing a request to vault a ACH Debit.
        /// </summary>
        [JsonProperty("ach_debit", NullValueHandling = NullValueHandling.Ignore)]
        public JsonValue AchDebit { get; set; }

        /// <summary>
        /// An API resource denoting a request to securely store a SEPA Debit.
        /// </summary>
        [JsonProperty("sepa_debit", NullValueHandling = NullValueHandling.Ignore)]
        public Models.SepaDebitRequest SepaDebit { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"BankRequest : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is BankRequest other &&
                (this.AchDebit == null && other.AchDebit == null ||
                 this.AchDebit?.Equals(other.AchDebit) == true) &&
                (this.SepaDebit == null && other.SepaDebit == null ||
                 this.SepaDebit?.Equals(other.SepaDebit) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"AchDebit = {(this.AchDebit == null ? "null" : this.AchDebit.ToString())}");
            toStringOutput.Add($"SepaDebit = {(this.SepaDebit == null ? "null" : this.SepaDebit.ToString())}");
        }
    }
}