// <copyright file="BillingCycleOverride.cs" company="APIMatic">
// PaypalServerSdk.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using PaypalServerSdk.Standard;
using PaypalServerSdk.Standard.Utilities;

namespace PaypalServerSdk.Standard.Models
{
    /// <summary>
    /// BillingCycleOverride.
    /// </summary>
    public class BillingCycleOverride
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BillingCycleOverride"/> class.
        /// </summary>
        public BillingCycleOverride()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="BillingCycleOverride"/> class.
        /// </summary>
        /// <param name="sequence">sequence.</param>
        /// <param name="pricingScheme">pricing_scheme.</param>
        /// <param name="totalCycles">total_cycles.</param>
        public BillingCycleOverride(
            int sequence,
            Models.SubscriptionPricingScheme pricingScheme = null,
            int? totalCycles = null)
        {
            this.PricingScheme = pricingScheme;
            this.Sequence = sequence;
            this.TotalCycles = totalCycles;
        }

        /// <summary>
        /// The pricing scheme details.
        /// </summary>
        [JsonProperty("pricing_scheme", NullValueHandling = NullValueHandling.Ignore)]
        public Models.SubscriptionPricingScheme PricingScheme { get; set; }

        /// <summary>
        /// The order in which this cycle is to run among other billing cycles. For example, a trial billing cycle has a `sequence` of `1` while a regular billing cycle has a `sequence` of `2`, so that trial cycle runs before the regular cycle.
        /// </summary>
        [JsonProperty("sequence")]
        public int Sequence { get; set; }

        /// <summary>
        /// The number of times this billing cycle gets executed. Trial billing cycles can only be executed a finite number of times (value between 1 and 999 for total_cycles). Regular billing cycles can be executed infinite times (value of 0 for total_cycles) or a finite number of times (value between 1 and 999 for total_cycles).
        /// </summary>
        [JsonProperty("total_cycles", NullValueHandling = NullValueHandling.Ignore)]
        public int? TotalCycles { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"BillingCycleOverride : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is BillingCycleOverride other &&
                (this.PricingScheme == null && other.PricingScheme == null ||
                 this.PricingScheme?.Equals(other.PricingScheme) == true) &&
                (this.Sequence.Equals(other.Sequence)) &&
                (this.TotalCycles == null && other.TotalCycles == null ||
                 this.TotalCycles?.Equals(other.TotalCycles) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"PricingScheme = {(this.PricingScheme == null ? "null" : this.PricingScheme.ToString())}");
            toStringOutput.Add($"Sequence = {this.Sequence}");
            toStringOutput.Add($"TotalCycles = {(this.TotalCycles == null ? "null" : this.TotalCycles.ToString())}");
        }
    }
}