// <copyright file="CancelSubscriptionRequest.cs" company="APIMatic">
// PaypalServerSdk.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace PaypalServerSdk.Standard.Models
{
    /// <summary>
    /// CancelSubscriptionRequest.
    /// </summary>
    public class CancelSubscriptionRequest
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CancelSubscriptionRequest"/> class.
        /// </summary>
        public CancelSubscriptionRequest()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CancelSubscriptionRequest"/> class.
        /// </summary>
        /// <param name="reason">reason.</param>
        public CancelSubscriptionRequest(
            string reason)
        {
            this.Reason = reason;
        }

        /// <summary>
        /// The reason for the cancellation of a subscription.
        /// </summary>
        [JsonProperty("reason")]
        public string Reason { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"CancelSubscriptionRequest : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is CancelSubscriptionRequest other &&
                (this.Reason == null && other.Reason == null ||
                 this.Reason?.Equals(other.Reason) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Reason = {this.Reason ?? "null"}");
        }
    }
}