// <copyright file="CaptureStatusWithDetails.cs" company="APIMatic">
// PaypalServerSdk.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace PaypalServerSdk.Standard.Models
{
    /// <summary>
    /// CaptureStatusWithDetails.
    /// </summary>
    public class CaptureStatusWithDetails
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CaptureStatusWithDetails"/> class.
        /// </summary>
        public CaptureStatusWithDetails()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CaptureStatusWithDetails"/> class.
        /// </summary>
        /// <param name="status">status.</param>
        /// <param name="statusDetails">status_details.</param>
        public CaptureStatusWithDetails(
            Models.CaptureStatus? status = null,
            Models.CaptureStatusDetails statusDetails = null)
        {
            this.Status = status;
            this.StatusDetails = statusDetails;
        }

        /// <summary>
        /// The status of the captured payment.
        /// </summary>
        [JsonProperty("status", NullValueHandling = NullValueHandling.Ignore)]
        public Models.CaptureStatus? Status { get; set; }

        /// <summary>
        /// The details of the captured payment status.
        /// </summary>
        [JsonProperty("status_details", NullValueHandling = NullValueHandling.Ignore)]
        public Models.CaptureStatusDetails StatusDetails { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"CaptureStatusWithDetails : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is CaptureStatusWithDetails other &&
                (this.Status == null && other.Status == null ||
                 this.Status?.Equals(other.Status) == true) &&
                (this.StatusDetails == null && other.StatusDetails == null ||
                 this.StatusDetails?.Equals(other.StatusDetails) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Status = {(this.Status == null ? "null" : this.Status.ToString())}");
            toStringOutput.Add($"StatusDetails = {(this.StatusDetails == null ? "null" : this.StatusDetails.ToString())}");
        }
    }
}