// <copyright file="CaptureSubscriptionRequest.cs" company="APIMatic">
// PaypalServerSdk.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using PaypalServerSdk.Standard;
using PaypalServerSdk.Standard.Utilities;

namespace PaypalServerSdk.Standard.Models
{
    /// <summary>
    /// CaptureSubscriptionRequest.
    /// </summary>
    public class CaptureSubscriptionRequest
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CaptureSubscriptionRequest"/> class.
        /// </summary>
        public CaptureSubscriptionRequest()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CaptureSubscriptionRequest"/> class.
        /// </summary>
        /// <param name="note">note.</param>
        /// <param name="captureType">capture_type.</param>
        /// <param name="amount">amount.</param>
        public CaptureSubscriptionRequest(
            string note,
            Models.CaptureType captureType,
            Models.Money amount)
        {
            this.Note = note;
            this.CaptureType = captureType;
            this.Amount = amount;
        }

        /// <summary>
        /// The reason or note for the subscription charge.
        /// </summary>
        [JsonProperty("note")]
        public string Note { get; set; }

        /// <summary>
        /// The type of capture.
        /// </summary>
        [JsonProperty("capture_type")]
        public Models.CaptureType CaptureType { get; set; }

        /// <summary>
        /// The currency and amount for a financial transaction, such as a balance or payment due.
        /// </summary>
        [JsonProperty("amount")]
        public Models.Money Amount { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"CaptureSubscriptionRequest : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is CaptureSubscriptionRequest other &&
                (this.Note == null && other.Note == null ||
                 this.Note?.Equals(other.Note) == true) &&
                (this.CaptureType.Equals(other.CaptureType)) &&
                (this.Amount == null && other.Amount == null ||
                 this.Amount?.Equals(other.Amount) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Note = {this.Note ?? "null"}");
            toStringOutput.Add($"CaptureType = {this.CaptureType}");
            toStringOutput.Add($"Amount = {(this.Amount == null ? "null" : this.Amount.ToString())}");
        }
    }
}