// <copyright file="CycleExecution.cs" company="APIMatic">
// PaypalServerSdk.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace PaypalServerSdk.Standard.Models
{
    /// <summary>
    /// CycleExecution.
    /// </summary>
    public class CycleExecution
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CycleExecution"/> class.
        /// </summary>
        public CycleExecution()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CycleExecution"/> class.
        /// </summary>
        /// <param name="tenureType">tenure_type.</param>
        /// <param name="sequence">sequence.</param>
        /// <param name="cyclesCompleted">cycles_completed.</param>
        /// <param name="cyclesRemaining">cycles_remaining.</param>
        /// <param name="currentPricingSchemeVersion">current_pricing_scheme_version.</param>
        /// <param name="totalCycles">total_cycles.</param>
        public CycleExecution(
            Models.TenureType tenureType,
            int sequence,
            int cyclesCompleted,
            int? cyclesRemaining = null,
            int? currentPricingSchemeVersion = null,
            int? totalCycles = null)
        {
            this.TenureType = tenureType;
            this.Sequence = sequence;
            this.CyclesCompleted = cyclesCompleted;
            this.CyclesRemaining = cyclesRemaining;
            this.CurrentPricingSchemeVersion = currentPricingSchemeVersion;
            this.TotalCycles = totalCycles;
        }

        /// <summary>
        /// The type of the billing cycle.
        /// </summary>
        [JsonProperty("tenure_type")]
        public Models.TenureType TenureType { get; set; }

        /// <summary>
        /// The order in which to run this cycle among other billing cycles.
        /// </summary>
        [JsonProperty("sequence")]
        public int Sequence { get; set; }

        /// <summary>
        /// The number of billing cycles that have completed.
        /// </summary>
        [JsonProperty("cycles_completed")]
        public int CyclesCompleted { get; set; }

        /// <summary>
        /// For a finite billing cycle, cycles_remaining is the number of remaining cycles. For an infinite billing cycle, cycles_remaining is set as 0.
        /// </summary>
        [JsonProperty("cycles_remaining", NullValueHandling = NullValueHandling.Ignore)]
        public int? CyclesRemaining { get; set; }

        /// <summary>
        /// The active pricing scheme version for the billing cycle.
        /// </summary>
        [JsonProperty("current_pricing_scheme_version", NullValueHandling = NullValueHandling.Ignore)]
        public int? CurrentPricingSchemeVersion { get; set; }

        /// <summary>
        /// The number of times this billing cycle gets executed. Trial billing cycles can only be executed a finite number of times (value between 1 and 999 for total_cycles). Regular billing cycles can be executed infinite times (value of 0 for total_cycles) or a finite number of times (value between 1 and 999 for total_cycles).
        /// </summary>
        [JsonProperty("total_cycles", NullValueHandling = NullValueHandling.Ignore)]
        public int? TotalCycles { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"CycleExecution : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is CycleExecution other &&
                (this.TenureType.Equals(other.TenureType)) &&
                (this.Sequence.Equals(other.Sequence)) &&
                (this.CyclesCompleted.Equals(other.CyclesCompleted)) &&
                (this.CyclesRemaining == null && other.CyclesRemaining == null ||
                 this.CyclesRemaining?.Equals(other.CyclesRemaining) == true) &&
                (this.CurrentPricingSchemeVersion == null && other.CurrentPricingSchemeVersion == null ||
                 this.CurrentPricingSchemeVersion?.Equals(other.CurrentPricingSchemeVersion) == true) &&
                (this.TotalCycles == null && other.TotalCycles == null ||
                 this.TotalCycles?.Equals(other.TotalCycles) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"TenureType = {this.TenureType}");
            toStringOutput.Add($"Sequence = {this.Sequence}");
            toStringOutput.Add($"CyclesCompleted = {this.CyclesCompleted}");
            toStringOutput.Add($"CyclesRemaining = {(this.CyclesRemaining == null ? "null" : this.CyclesRemaining.ToString())}");
            toStringOutput.Add($"CurrentPricingSchemeVersion = {(this.CurrentPricingSchemeVersion == null ? "null" : this.CurrentPricingSchemeVersion.ToString())}");
            toStringOutput.Add($"TotalCycles = {(this.TotalCycles == null ? "null" : this.TotalCycles.ToString())}");
        }
    }
}