// <copyright file="DisputeCategory.cs" company="APIMatic">
// PaypalServerSdk.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace PaypalServerSdk.Standard.Models
{
    /// <summary>
    /// DisputeCategory.
    /// </summary>

    [JsonConverter(typeof(UnknownEnumConverter<StringEnumConverter>), nameof(_Unknown))]
    public enum DisputeCategory
    {
        /// <summary>
        ///The payer paid for an item that they did not receive.
        /// ItemNotReceived.
        /// </summary>
        [EnumMember(Value = "ITEM_NOT_RECEIVED")]
        ItemNotReceived,

        /// <summary>
        ///The payer did not authorize the payment.
        /// UnauthorizedTransaction.
        /// </summary>
        [EnumMember(Value = "UNAUTHORIZED_TRANSACTION")]
        UnauthorizedTransaction,

        /// <summary>
        /// Unknown values will be mapped by this enum member.
        /// </summary>
        _Unknown
    }
}