// <copyright file="Item.cs" company="APIMatic">
// PaypalServerSdk.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace PaypalServerSdk.Standard.Models
{
    /// <summary>
    /// Item.
    /// </summary>
    public class Item
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Item"/> class.
        /// </summary>
        public Item()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Item"/> class.
        /// </summary>
        /// <param name="name">name.</param>
        /// <param name="unitAmount">unit_amount.</param>
        /// <param name="quantity">quantity.</param>
        /// <param name="tax">tax.</param>
        /// <param name="description">description.</param>
        /// <param name="sku">sku.</param>
        /// <param name="url">url.</param>
        /// <param name="category">category.</param>
        /// <param name="imageUrl">image_url.</param>
        /// <param name="upc">upc.</param>
        /// <param name="billingPlan">billing_plan.</param>
        public Item(
            string name,
            Models.Money unitAmount,
            string quantity,
            Models.Money tax = null,
            string description = null,
            string sku = null,
            string url = null,
            Models.ItemCategory? category = null,
            string imageUrl = null,
            Models.UniversalProductCode upc = null,
            Models.OrderBillingPlan billingPlan = null)
        {
            this.Name = name;
            this.UnitAmount = unitAmount;
            this.Tax = tax;
            this.Quantity = quantity;
            this.Description = description;
            this.Sku = sku;
            this.Url = url;
            this.Category = category;
            this.ImageUrl = imageUrl;
            this.Upc = upc;
            this.BillingPlan = billingPlan;
        }

        /// <summary>
        /// The item name or title.
        /// </summary>
        [JsonProperty("name")]
        public string Name { get; set; }

        /// <summary>
        /// The currency and amount for a financial transaction, such as a balance or payment due.
        /// </summary>
        [JsonProperty("unit_amount")]
        public Models.Money UnitAmount { get; set; }

        /// <summary>
        /// The currency and amount for a financial transaction, such as a balance or payment due.
        /// </summary>
        [JsonProperty("tax", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Money Tax { get; set; }

        /// <summary>
        /// The item quantity. Must be a whole number.
        /// </summary>
        [JsonProperty("quantity")]
        public string Quantity { get; set; }

        /// <summary>
        /// The detailed item description.
        /// </summary>
        [JsonProperty("description", NullValueHandling = NullValueHandling.Ignore)]
        public string Description { get; set; }

        /// <summary>
        /// The stock keeping unit (SKU) for the item.
        /// </summary>
        [JsonProperty("sku", NullValueHandling = NullValueHandling.Ignore)]
        public string Sku { get; set; }

        /// <summary>
        /// The URL to the item being purchased. Visible to buyer and used in buyer experiences.
        /// </summary>
        [JsonProperty("url", NullValueHandling = NullValueHandling.Ignore)]
        public string Url { get; set; }

        /// <summary>
        /// The item category type.
        /// </summary>
        [JsonProperty("category", NullValueHandling = NullValueHandling.Ignore)]
        public Models.ItemCategory? Category { get; set; }

        /// <summary>
        /// The URL of the item's image. File type and size restrictions apply. An image that violates these restrictions will not be honored.
        /// </summary>
        [JsonProperty("image_url", NullValueHandling = NullValueHandling.Ignore)]
        public string ImageUrl { get; set; }

        /// <summary>
        /// The Universal Product Code of the item.
        /// </summary>
        [JsonProperty("upc", NullValueHandling = NullValueHandling.Ignore)]
        public Models.UniversalProductCode Upc { get; set; }

        /// <summary>
        /// Metadata for merchant-managed recurring billing plans. Valid only during the saved payment method token or billing agreement creation.
        /// </summary>
        [JsonProperty("billing_plan", NullValueHandling = NullValueHandling.Ignore)]
        public Models.OrderBillingPlan BillingPlan { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"Item : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is Item other &&
                (this.Name == null && other.Name == null ||
                 this.Name?.Equals(other.Name) == true) &&
                (this.UnitAmount == null && other.UnitAmount == null ||
                 this.UnitAmount?.Equals(other.UnitAmount) == true) &&
                (this.Tax == null && other.Tax == null ||
                 this.Tax?.Equals(other.Tax) == true) &&
                (this.Quantity == null && other.Quantity == null ||
                 this.Quantity?.Equals(other.Quantity) == true) &&
                (this.Description == null && other.Description == null ||
                 this.Description?.Equals(other.Description) == true) &&
                (this.Sku == null && other.Sku == null ||
                 this.Sku?.Equals(other.Sku) == true) &&
                (this.Url == null && other.Url == null ||
                 this.Url?.Equals(other.Url) == true) &&
                (this.Category == null && other.Category == null ||
                 this.Category?.Equals(other.Category) == true) &&
                (this.ImageUrl == null && other.ImageUrl == null ||
                 this.ImageUrl?.Equals(other.ImageUrl) == true) &&
                (this.Upc == null && other.Upc == null ||
                 this.Upc?.Equals(other.Upc) == true) &&
                (this.BillingPlan == null && other.BillingPlan == null ||
                 this.BillingPlan?.Equals(other.BillingPlan) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Name = {this.Name ?? "null"}");
            toStringOutput.Add($"UnitAmount = {(this.UnitAmount == null ? "null" : this.UnitAmount.ToString())}");
            toStringOutput.Add($"Tax = {(this.Tax == null ? "null" : this.Tax.ToString())}");
            toStringOutput.Add($"Quantity = {this.Quantity ?? "null"}");
            toStringOutput.Add($"Description = {this.Description ?? "null"}");
            toStringOutput.Add($"Sku = {this.Sku ?? "null"}");
            toStringOutput.Add($"Url = {this.Url ?? "null"}");
            toStringOutput.Add($"Category = {(this.Category == null ? "null" : this.Category.ToString())}");
            toStringOutput.Add($"ImageUrl = {this.ImageUrl ?? "null"}");
            toStringOutput.Add($"Upc = {(this.Upc == null ? "null" : this.Upc.ToString())}");
            toStringOutput.Add($"BillingPlan = {(this.BillingPlan == null ? "null" : this.BillingPlan.ToString())}");
        }
    }
}