// <copyright file="LiabilityShiftIndicator.cs" company="APIMatic">
// PaypalServerSdk.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace PaypalServerSdk.Standard.Models
{
    /// <summary>
    /// LiabilityShiftIndicator.
    /// </summary>

    [JsonConverter(typeof(UnknownEnumConverter<StringEnumConverter>), nameof(_Unknown))]
    public enum LiabilityShiftIndicator
    {
        /// <summary>
        ///Liability is with the merchant.
        /// No.
        /// </summary>
        [EnumMember(Value = "NO")]
        No,

        /// <summary>
        ///Liability may shift to the card issuer.
        /// Possible.
        /// </summary>
        [EnumMember(Value = "POSSIBLE")]
        Possible,

        /// <summary>
        ///The authentication system is not available.
        /// Unknown.
        /// </summary>
        [EnumMember(Value = "UNKNOWN")]
        Unknown,

        /// <summary>
        /// Unknown values will be mapped by this enum member.
        /// </summary>
        _Unknown
    }
}