// <copyright file="ListSubscriptionsInput.cs" company="APIMatic">
// PaypalServerSdk.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace PaypalServerSdk.Standard.Models
{
    /// <summary>
    /// ListSubscriptionsInput.
    /// </summary>
    public class ListSubscriptionsInput
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ListSubscriptionsInput"/> class.
        /// </summary>
        public ListSubscriptionsInput()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ListSubscriptionsInput"/> class.
        /// </summary>
        /// <param name="planIds">plan_ids.</param>
        /// <param name="statuses">statuses.</param>
        /// <param name="createdAfter">created_after.</param>
        /// <param name="createdBefore">created_before.</param>
        /// <param name="statusUpdatedBefore">status_updated_before.</param>
        /// <param name="statusUpdatedAfter">status_updated_after.</param>
        /// <param name="filter">filter.</param>
        /// <param name="pageSize">page_size.</param>
        /// <param name="page">page.</param>
        /// <param name="customerIds">customer_ids.</param>
        public ListSubscriptionsInput(
            string planIds = null,
            string statuses = null,
            string createdAfter = null,
            string createdBefore = null,
            string statusUpdatedBefore = null,
            string statusUpdatedAfter = null,
            string filter = null,
            int? pageSize = 10,
            int? page = 1,
            List<string> customerIds = null)
        {
            this.PlanIds = planIds;
            this.Statuses = statuses;
            this.CreatedAfter = createdAfter;
            this.CreatedBefore = createdBefore;
            this.StatusUpdatedBefore = statusUpdatedBefore;
            this.StatusUpdatedAfter = statusUpdatedAfter;
            this.Filter = filter;
            this.PageSize = pageSize;
            this.Page = page;
            this.CustomerIds = customerIds;
        }

        /// <summary>
        /// Filters the response by list of plan IDs. Filter supports upto 70 plan IDs. URLs should not exceed a length of 2000 characters.
        /// </summary>
        [JsonProperty("plan_ids", NullValueHandling = NullValueHandling.Ignore)]
        public string PlanIds { get; set; }

        /// <summary>
        /// Filters the response by list of subscription statuses.
        /// </summary>
        [JsonProperty("statuses", NullValueHandling = NullValueHandling.Ignore)]
        public string Statuses { get; set; }

        /// <summary>
        /// Filters the response by subscription creation start time for a range of subscriptions.
        /// </summary>
        [JsonProperty("created_after", NullValueHandling = NullValueHandling.Ignore)]
        public string CreatedAfter { get; set; }

        /// <summary>
        /// Filters the response by subscription creation end time for a range of subscriptions.
        /// </summary>
        [JsonProperty("created_before", NullValueHandling = NullValueHandling.Ignore)]
        public string CreatedBefore { get; set; }

        /// <summary>
        /// Filters the response by status update start time for a range of subscriptions.
        /// </summary>
        [JsonProperty("status_updated_before", NullValueHandling = NullValueHandling.Ignore)]
        public string StatusUpdatedBefore { get; set; }

        /// <summary>
        /// Filters the response by status update end time for a range of subscriptions.
        /// </summary>
        [JsonProperty("status_updated_after", NullValueHandling = NullValueHandling.Ignore)]
        public string StatusUpdatedAfter { get; set; }

        /// <summary>
        /// Filter the response using complex expressions that could use comparison operators like ge, gt, le, lt and logical operators such as 'and' and 'or'.
        /// </summary>
        [JsonProperty("filter", NullValueHandling = NullValueHandling.Ignore)]
        public string Filter { get; set; }

        /// <summary>
        /// The number of items to return in the response.
        /// </summary>
        [JsonProperty("page_size", NullValueHandling = NullValueHandling.Ignore)]
        public int? PageSize { get; set; }

        /// <summary>
        /// A non-zero integer which is the start index of the entire list of items to return in the response. The combination of `page=1` and `page_size=20` returns the first 20 items. The combination of `page=2` and `page_size=20` returns the next 20 items.
        /// </summary>
        [JsonProperty("page", NullValueHandling = NullValueHandling.Ignore)]
        public int? Page { get; set; }

        /// <summary>
        /// Filters the response by comma separated vault customer IDs (FSS subscriptions only).
        /// </summary>
        [JsonProperty("customer_ids", NullValueHandling = NullValueHandling.Ignore)]
        public List<string> CustomerIds { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ListSubscriptionsInput : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is ListSubscriptionsInput other &&
                (this.PlanIds == null && other.PlanIds == null ||
                 this.PlanIds?.Equals(other.PlanIds) == true) &&
                (this.Statuses == null && other.Statuses == null ||
                 this.Statuses?.Equals(other.Statuses) == true) &&
                (this.CreatedAfter == null && other.CreatedAfter == null ||
                 this.CreatedAfter?.Equals(other.CreatedAfter) == true) &&
                (this.CreatedBefore == null && other.CreatedBefore == null ||
                 this.CreatedBefore?.Equals(other.CreatedBefore) == true) &&
                (this.StatusUpdatedBefore == null && other.StatusUpdatedBefore == null ||
                 this.StatusUpdatedBefore?.Equals(other.StatusUpdatedBefore) == true) &&
                (this.StatusUpdatedAfter == null && other.StatusUpdatedAfter == null ||
                 this.StatusUpdatedAfter?.Equals(other.StatusUpdatedAfter) == true) &&
                (this.Filter == null && other.Filter == null ||
                 this.Filter?.Equals(other.Filter) == true) &&
                (this.PageSize == null && other.PageSize == null ||
                 this.PageSize?.Equals(other.PageSize) == true) &&
                (this.Page == null && other.Page == null ||
                 this.Page?.Equals(other.Page) == true) &&
                (this.CustomerIds == null && other.CustomerIds == null ||
                 this.CustomerIds?.Equals(other.CustomerIds) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"PlanIds = {this.PlanIds ?? "null"}");
            toStringOutput.Add($"Statuses = {this.Statuses ?? "null"}");
            toStringOutput.Add($"CreatedAfter = {this.CreatedAfter ?? "null"}");
            toStringOutput.Add($"CreatedBefore = {this.CreatedBefore ?? "null"}");
            toStringOutput.Add($"StatusUpdatedBefore = {this.StatusUpdatedBefore ?? "null"}");
            toStringOutput.Add($"StatusUpdatedAfter = {this.StatusUpdatedAfter ?? "null"}");
            toStringOutput.Add($"Filter = {this.Filter ?? "null"}");
            toStringOutput.Add($"PageSize = {(this.PageSize == null ? "null" : this.PageSize.ToString())}");
            toStringOutput.Add($"Page = {(this.Page == null ? "null" : this.Page.ToString())}");
            toStringOutput.Add($"CustomerIds = {(this.CustomerIds == null ? "null" : $"[{string.Join(", ", this.CustomerIds)} ]")}");
        }
    }
}