// <copyright file="MobileWebContext.cs" company="APIMatic">
// PaypalServerSdk.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using PaypalServerSdk.Standard;
using PaypalServerSdk.Standard.Utilities;

namespace PaypalServerSdk.Standard.Models
{
    /// <summary>
    /// MobileWebContext.
    /// </summary>
    public class MobileWebContext
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MobileWebContext"/> class.
        /// </summary>
        public MobileWebContext()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MobileWebContext"/> class.
        /// </summary>
        /// <param name="returnFlow">return_flow.</param>
        /// <param name="buyerUserAgent">buyer_user_agent.</param>
        public MobileWebContext(
            Models.MobileReturnFlow? returnFlow = Models.MobileReturnFlow.Auto,
            string buyerUserAgent = null)
        {
            this.ReturnFlow = returnFlow;
            this.BuyerUserAgent = buyerUserAgent;
        }

        /// <summary>
        /// Merchant preference on how the buyer can navigate back to merchant website post approving the transaction on the PayPal App.
        /// </summary>
        [JsonProperty("return_flow", NullValueHandling = NullValueHandling.Ignore)]
        public Models.MobileReturnFlow? ReturnFlow { get; set; }

        /// <summary>
        /// User agent from the request originating from the buyer's device. This will be used to identify the buyer's operating system and browser versions. NOTE: Merchants must not alter or modify the buyer's device user agent.
        /// </summary>
        [JsonProperty("buyer_user_agent", NullValueHandling = NullValueHandling.Ignore)]
        public string BuyerUserAgent { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"MobileWebContext : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is MobileWebContext other &&
                (this.ReturnFlow == null && other.ReturnFlow == null ||
                 this.ReturnFlow?.Equals(other.ReturnFlow) == true) &&
                (this.BuyerUserAgent == null && other.BuyerUserAgent == null ||
                 this.BuyerUserAgent?.Equals(other.BuyerUserAgent) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"ReturnFlow = {(this.ReturnFlow == null ? "null" : this.ReturnFlow.ToString())}");
            toStringOutput.Add($"BuyerUserAgent = {this.BuyerUserAgent ?? "null"}");
        }
    }
}