// <copyright file="ModifySubscriptionResponse.cs" company="APIMatic">
// PaypalServerSdk.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace PaypalServerSdk.Standard.Models
{
    /// <summary>
    /// ModifySubscriptionResponse.
    /// </summary>
    public class ModifySubscriptionResponse
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ModifySubscriptionResponse"/> class.
        /// </summary>
        public ModifySubscriptionResponse()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ModifySubscriptionResponse"/> class.
        /// </summary>
        /// <param name="planId">plan_id.</param>
        /// <param name="quantity">quantity.</param>
        /// <param name="shippingAmount">shipping_amount.</param>
        /// <param name="shippingAddress">shipping_address.</param>
        /// <param name="plan">plan.</param>
        /// <param name="planOverridden">plan_overridden.</param>
        /// <param name="links">links.</param>
        public ModifySubscriptionResponse(
            string planId = null,
            string quantity = null,
            Models.Money shippingAmount = null,
            Models.ShippingDetails shippingAddress = null,
            Models.PlanOverride plan = null,
            bool? planOverridden = null,
            List<Models.LinkDescription> links = null)
        {
            this.PlanId = planId;
            this.Quantity = quantity;
            this.ShippingAmount = shippingAmount;
            this.ShippingAddress = shippingAddress;
            this.Plan = plan;
            this.PlanOverridden = planOverridden;
            this.Links = links;
        }

        /// <summary>
        /// The unique PayPal-generated ID for the plan.
        /// </summary>
        [JsonProperty("plan_id", NullValueHandling = NullValueHandling.Ignore)]
        public string PlanId { get; set; }

        /// <summary>
        /// The quantity of the product or service in the subscription.
        /// </summary>
        [JsonProperty("quantity", NullValueHandling = NullValueHandling.Ignore)]
        public string Quantity { get; set; }

        /// <summary>
        /// The currency and amount for a financial transaction, such as a balance or payment due.
        /// </summary>
        [JsonProperty("shipping_amount", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Money ShippingAmount { get; set; }

        /// <summary>
        /// The shipping details.
        /// </summary>
        [JsonProperty("shipping_address", NullValueHandling = NullValueHandling.Ignore)]
        public Models.ShippingDetails ShippingAddress { get; set; }

        /// <summary>
        /// An inline plan object to customise the subscription. You can override plan level default attributes by providing customised values for the subscription in this object.
        /// </summary>
        [JsonProperty("plan", NullValueHandling = NullValueHandling.Ignore)]
        public Models.PlanOverride Plan { get; set; }

        /// <summary>
        /// Indicates whether the subscription has overridden any plan attributes.
        /// </summary>
        [JsonProperty("plan_overridden", NullValueHandling = NullValueHandling.Ignore)]
        public bool? PlanOverridden { get; set; }

        /// <summary>
        /// An array of request-related [HATEOAS links](/docs/api/reference/api-responses/#hateoas-links).
        /// </summary>
        [JsonProperty("links", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.LinkDescription> Links { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ModifySubscriptionResponse : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is ModifySubscriptionResponse other &&
                (this.PlanId == null && other.PlanId == null ||
                 this.PlanId?.Equals(other.PlanId) == true) &&
                (this.Quantity == null && other.Quantity == null ||
                 this.Quantity?.Equals(other.Quantity) == true) &&
                (this.ShippingAmount == null && other.ShippingAmount == null ||
                 this.ShippingAmount?.Equals(other.ShippingAmount) == true) &&
                (this.ShippingAddress == null && other.ShippingAddress == null ||
                 this.ShippingAddress?.Equals(other.ShippingAddress) == true) &&
                (this.Plan == null && other.Plan == null ||
                 this.Plan?.Equals(other.Plan) == true) &&
                (this.PlanOverridden == null && other.PlanOverridden == null ||
                 this.PlanOverridden?.Equals(other.PlanOverridden) == true) &&
                (this.Links == null && other.Links == null ||
                 this.Links?.Equals(other.Links) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"PlanId = {this.PlanId ?? "null"}");
            toStringOutput.Add($"Quantity = {this.Quantity ?? "null"}");
            toStringOutput.Add($"ShippingAmount = {(this.ShippingAmount == null ? "null" : this.ShippingAmount.ToString())}");
            toStringOutput.Add($"ShippingAddress = {(this.ShippingAddress == null ? "null" : this.ShippingAddress.ToString())}");
            toStringOutput.Add($"Plan = {(this.Plan == null ? "null" : this.Plan.ToString())}");
            toStringOutput.Add($"PlanOverridden = {(this.PlanOverridden == null ? "null" : this.PlanOverridden.ToString())}");
            toStringOutput.Add($"Links = {(this.Links == null ? "null" : $"[{string.Join(", ", this.Links)} ]")}");
        }
    }
}