// <copyright file="SearchTransactionsInput.cs" company="APIMatic">
// PaypalServerSdk.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace PaypalServerSdk.Standard.Models
{
    /// <summary>
    /// SearchTransactionsInput.
    /// </summary>
    public class SearchTransactionsInput
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SearchTransactionsInput"/> class.
        /// </summary>
        public SearchTransactionsInput()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SearchTransactionsInput"/> class.
        /// </summary>
        /// <param name="startDate">start_date.</param>
        /// <param name="endDate">end_date.</param>
        /// <param name="transactionId">transaction_id.</param>
        /// <param name="transactionType">transaction_type.</param>
        /// <param name="transactionStatus">transaction_status.</param>
        /// <param name="transactionAmount">transaction_amount.</param>
        /// <param name="transactionCurrency">transaction_currency.</param>
        /// <param name="paymentInstrumentType">payment_instrument_type.</param>
        /// <param name="storeId">store_id.</param>
        /// <param name="terminalId">terminal_id.</param>
        /// <param name="fields">fields.</param>
        /// <param name="balanceAffectingRecordsOnly">balance_affecting_records_only.</param>
        /// <param name="pageSize">page_size.</param>
        /// <param name="page">page.</param>
        public SearchTransactionsInput(
            string startDate,
            string endDate,
            string transactionId = null,
            string transactionType = null,
            string transactionStatus = null,
            string transactionAmount = null,
            string transactionCurrency = null,
            string paymentInstrumentType = null,
            string storeId = null,
            string terminalId = null,
            string fields = "transaction_info",
            string balanceAffectingRecordsOnly = "Y",
            int? pageSize = 100,
            int? page = 1)
        {
            this.StartDate = startDate;
            this.EndDate = endDate;
            this.TransactionId = transactionId;
            this.TransactionType = transactionType;
            this.TransactionStatus = transactionStatus;
            this.TransactionAmount = transactionAmount;
            this.TransactionCurrency = transactionCurrency;
            this.PaymentInstrumentType = paymentInstrumentType;
            this.StoreId = storeId;
            this.TerminalId = terminalId;
            this.Fields = fields;
            this.BalanceAffectingRecordsOnly = balanceAffectingRecordsOnly;
            this.PageSize = pageSize;
            this.Page = page;
        }

        /// <summary>
        /// Filters the transactions in the response by a start date and time, in [Internet date and time format](https://tools.ietf.org/html/rfc3339#section-5.6). Seconds are required. Fractional seconds are optional.
        /// </summary>
        [JsonProperty("start_date")]
        public string StartDate { get; set; }

        /// <summary>
        /// Filters the transactions in the response by an end date and time, in [Internet date and time format](https://tools.ietf.org/html/rfc3339#section-5.6). Seconds are required. Fractional seconds are optional. The maximum supported range is 31 days.
        /// </summary>
        [JsonProperty("end_date")]
        public string EndDate { get; set; }

        /// <summary>
        /// Filters the transactions in the response by a PayPal transaction ID. A valid transaction ID is 17 characters long, except for an order ID, which is 19 characters long. Note: A transaction ID is not unique in the reporting system. The response can list two transactions with the same ID. One transaction can be balance affecting while the other is non-balance affecting.
        /// </summary>
        [JsonProperty("transaction_id", NullValueHandling = NullValueHandling.Ignore)]
        public string TransactionId { get; set; }

        /// <summary>
        /// Filters the transactions in the response by a PayPal transaction event code. See [Transaction event codes](/docs/integration/direct/transaction-search/transaction-event-codes/).
        /// </summary>
        [JsonProperty("transaction_type", NullValueHandling = NullValueHandling.Ignore)]
        public string TransactionType { get; set; }

        /// <summary>
        /// Filters the transactions in the response by a PayPal transaction status code. Value is: Status code Description D PayPal or merchant rules denied the transaction. P The transaction is pending. The transaction was created but waits for another payment process to complete, such as an ACH transaction, before the status changes to S. S The transaction successfully completed without a denial and after any pending statuses. V A successful transaction was reversed and funds were refunded to the original sender.
        /// </summary>
        [JsonProperty("transaction_status", NullValueHandling = NullValueHandling.Ignore)]
        public string TransactionStatus { get; set; }

        /// <summary>
        /// Filters the transactions in the response by a gross transaction amount range. Specify the range as ` TO `, where ` ` is the lower limit of the gross PayPal transaction amount and ` ` is the upper limit of the gross transaction amount. Specify the amounts in lower denominations. For example, to search for transactions from $5.00 to $10.05, specify `[500 TO 1005]`. Note:The values must be URL encoded.
        /// </summary>
        [JsonProperty("transaction_amount", NullValueHandling = NullValueHandling.Ignore)]
        public string TransactionAmount { get; set; }

        /// <summary>
        /// Filters the transactions in the response by a [three-character ISO-4217 currency code](/api/rest/reference/currency-codes/) for the PayPal transaction currency.
        /// </summary>
        [JsonProperty("transaction_currency", NullValueHandling = NullValueHandling.Ignore)]
        public string TransactionCurrency { get; set; }

        /// <summary>
        /// Filters the transactions in the response by a payment instrument type. Value is either: CREDITCARD. Returns a direct credit card transaction with a corresponding value. DEBITCARD. Returns a debit card transaction with a corresponding value. If you omit this parameter, the API does not apply this filter.
        /// </summary>
        [JsonProperty("payment_instrument_type", NullValueHandling = NullValueHandling.Ignore)]
        public string PaymentInstrumentType { get; set; }

        /// <summary>
        /// Filters the transactions in the response by a store ID.
        /// </summary>
        [JsonProperty("store_id", NullValueHandling = NullValueHandling.Ignore)]
        public string StoreId { get; set; }

        /// <summary>
        /// Filters the transactions in the response by a terminal ID.
        /// </summary>
        [JsonProperty("terminal_id", NullValueHandling = NullValueHandling.Ignore)]
        public string TerminalId { get; set; }

        /// <summary>
        /// Indicates which fields appear in the response. Value is a single field or a comma-separated list of fields. The transaction_info value returns only the transaction details in the response. To include all fields in the response, specify fields=all. Valid fields are: transaction_info. The transaction information. Includes the ID of the PayPal account of the payee, the PayPal-generated transaction ID, the PayPal-generated base ID, the PayPal reference ID type, the transaction event code, the date and time when the transaction was initiated and was last updated, the transaction amounts including the PayPal fee, any discounts, insurance, the transaction status, and other information about the transaction. payer_info. The payer information. Includes the PayPal customer account ID and the payer's email address, primary phone number, name, country code, address, and whether the payer is verified or unverified. shipping_info. The shipping information. Includes the recipient's name, the shipping method for this order, the shipping address for this order, and the secondary address associated with this order. auction_info. The auction information. Includes the name of the auction site, the auction site URL, the ID of the customer who makes the purchase in the auction, and the date and time when the auction closes. cart_info. The cart information. Includes an array of item details, whether the item amount or the shipping amount already includes tax, and the ID of the invoice for PayPal-generated invoices. incentive_info. An array of incentive detail objects. Each object includes the incentive, such as a special offer or coupon, the incentive amount, and the incentive program code that identifies a merchant loyalty or incentive program. store_info. The store information. Includes the ID of the merchant store and the terminal ID for the checkout stand in the merchant store.
        /// </summary>
        [JsonProperty("fields", NullValueHandling = NullValueHandling.Ignore)]
        public string Fields { get; set; }

        /// <summary>
        /// Indicates whether the response includes only balance-impacting transactions or all transactions. Value is either: Y. The default. The response includes only balance transactions. N. The response includes all transactions.
        /// </summary>
        [JsonProperty("balance_affecting_records_only", NullValueHandling = NullValueHandling.Ignore)]
        public string BalanceAffectingRecordsOnly { get; set; }

        /// <summary>
        /// The number of items to return in the response. So, the combination of `page=1` and `page_size=20` returns the first 20 items. The combination of `page=2` and `page_size=20` returns the next 20 items.
        /// </summary>
        [JsonProperty("page_size", NullValueHandling = NullValueHandling.Ignore)]
        public int? PageSize { get; set; }

        /// <summary>
        /// The zero-relative start index of the entire list of items that are returned in the response. So, the combination of `page=1` and `page_size=20` returns the first 20 items.
        /// </summary>
        [JsonProperty("page", NullValueHandling = NullValueHandling.Ignore)]
        public int? Page { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"SearchTransactionsInput : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is SearchTransactionsInput other &&
                (this.StartDate == null && other.StartDate == null ||
                 this.StartDate?.Equals(other.StartDate) == true) &&
                (this.EndDate == null && other.EndDate == null ||
                 this.EndDate?.Equals(other.EndDate) == true) &&
                (this.TransactionId == null && other.TransactionId == null ||
                 this.TransactionId?.Equals(other.TransactionId) == true) &&
                (this.TransactionType == null && other.TransactionType == null ||
                 this.TransactionType?.Equals(other.TransactionType) == true) &&
                (this.TransactionStatus == null && other.TransactionStatus == null ||
                 this.TransactionStatus?.Equals(other.TransactionStatus) == true) &&
                (this.TransactionAmount == null && other.TransactionAmount == null ||
                 this.TransactionAmount?.Equals(other.TransactionAmount) == true) &&
                (this.TransactionCurrency == null && other.TransactionCurrency == null ||
                 this.TransactionCurrency?.Equals(other.TransactionCurrency) == true) &&
                (this.PaymentInstrumentType == null && other.PaymentInstrumentType == null ||
                 this.PaymentInstrumentType?.Equals(other.PaymentInstrumentType) == true) &&
                (this.StoreId == null && other.StoreId == null ||
                 this.StoreId?.Equals(other.StoreId) == true) &&
                (this.TerminalId == null && other.TerminalId == null ||
                 this.TerminalId?.Equals(other.TerminalId) == true) &&
                (this.Fields == null && other.Fields == null ||
                 this.Fields?.Equals(other.Fields) == true) &&
                (this.BalanceAffectingRecordsOnly == null && other.BalanceAffectingRecordsOnly == null ||
                 this.BalanceAffectingRecordsOnly?.Equals(other.BalanceAffectingRecordsOnly) == true) &&
                (this.PageSize == null && other.PageSize == null ||
                 this.PageSize?.Equals(other.PageSize) == true) &&
                (this.Page == null && other.Page == null ||
                 this.Page?.Equals(other.Page) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"StartDate = {this.StartDate ?? "null"}");
            toStringOutput.Add($"EndDate = {this.EndDate ?? "null"}");
            toStringOutput.Add($"TransactionId = {this.TransactionId ?? "null"}");
            toStringOutput.Add($"TransactionType = {this.TransactionType ?? "null"}");
            toStringOutput.Add($"TransactionStatus = {this.TransactionStatus ?? "null"}");
            toStringOutput.Add($"TransactionAmount = {this.TransactionAmount ?? "null"}");
            toStringOutput.Add($"TransactionCurrency = {this.TransactionCurrency ?? "null"}");
            toStringOutput.Add($"PaymentInstrumentType = {this.PaymentInstrumentType ?? "null"}");
            toStringOutput.Add($"StoreId = {this.StoreId ?? "null"}");
            toStringOutput.Add($"TerminalId = {this.TerminalId ?? "null"}");
            toStringOutput.Add($"Fields = {this.Fields ?? "null"}");
            toStringOutput.Add($"BalanceAffectingRecordsOnly = {this.BalanceAffectingRecordsOnly ?? "null"}");
            toStringOutput.Add($"PageSize = {(this.PageSize == null ? "null" : this.PageSize.ToString())}");
            toStringOutput.Add($"Page = {(this.Page == null ? "null" : this.Page.ToString())}");
        }
    }
}