// <copyright file="SearchResponse.cs" company="APIMatic">
// PaypalServerSdk.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace PaypalServerSdk.Standard.Models
{
    /// <summary>
    /// SearchResponse.
    /// </summary>
    public class SearchResponse
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SearchResponse"/> class.
        /// </summary>
        public SearchResponse()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SearchResponse"/> class.
        /// </summary>
        /// <param name="transactionDetails">transaction_details.</param>
        /// <param name="accountNumber">account_number.</param>
        /// <param name="startDate">start_date.</param>
        /// <param name="endDate">end_date.</param>
        /// <param name="lastRefreshedDatetime">last_refreshed_datetime.</param>
        /// <param name="page">page.</param>
        /// <param name="totalItems">total_items.</param>
        /// <param name="totalPages">total_pages.</param>
        /// <param name="links">links.</param>
        public SearchResponse(
            List<Models.TransactionDetails> transactionDetails = null,
            string accountNumber = null,
            string startDate = null,
            string endDate = null,
            string lastRefreshedDatetime = null,
            int? page = null,
            int? totalItems = null,
            int? totalPages = null,
            List<Models.LinkDescription> links = null)
        {
            this.TransactionDetails = transactionDetails;
            this.AccountNumber = accountNumber;
            this.StartDate = startDate;
            this.EndDate = endDate;
            this.LastRefreshedDatetime = lastRefreshedDatetime;
            this.Page = page;
            this.TotalItems = totalItems;
            this.TotalPages = totalPages;
            this.Links = links;
        }

        /// <summary>
        /// An array of transaction detail objects.
        /// </summary>
        [JsonProperty("transaction_details", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.TransactionDetails> TransactionDetails { get; set; }

        /// <summary>
        /// The merchant account number.
        /// </summary>
        [JsonProperty("account_number", NullValueHandling = NullValueHandling.Ignore)]
        public string AccountNumber { get; set; }

        /// <summary>
        /// The date and time, in [Internet date and time format](https://tools.ietf.org/html/rfc3339#section-5.6). Seconds are required while fractional seconds are optional. Note: The regular expression provides guidance but does not reject all invalid dates.
        /// </summary>
        [JsonProperty("start_date", NullValueHandling = NullValueHandling.Ignore)]
        public string StartDate { get; set; }

        /// <summary>
        /// The date and time, in [Internet date and time format](https://tools.ietf.org/html/rfc3339#section-5.6). Seconds are required while fractional seconds are optional. Note: The regular expression provides guidance but does not reject all invalid dates.
        /// </summary>
        [JsonProperty("end_date", NullValueHandling = NullValueHandling.Ignore)]
        public string EndDate { get; set; }

        /// <summary>
        /// The date and time, in [Internet date and time format](https://tools.ietf.org/html/rfc3339#section-5.6). Seconds are required while fractional seconds are optional. Note: The regular expression provides guidance but does not reject all invalid dates.
        /// </summary>
        [JsonProperty("last_refreshed_datetime", NullValueHandling = NullValueHandling.Ignore)]
        public string LastRefreshedDatetime { get; set; }

        /// <summary>
        /// A zero-relative index of transactions.
        /// </summary>
        [JsonProperty("page", NullValueHandling = NullValueHandling.Ignore)]
        public int? Page { get; set; }

        /// <summary>
        /// The total number of transactions as an integer beginning with the specified `page` in the full result and not just in this response.
        /// </summary>
        [JsonProperty("total_items", NullValueHandling = NullValueHandling.Ignore)]
        public int? TotalItems { get; set; }

        /// <summary>
        /// The total number of pages, as an `integer`, when the `total_items` is divided into pages of the specified `page_size`.
        /// </summary>
        [JsonProperty("total_pages", NullValueHandling = NullValueHandling.Ignore)]
        public int? TotalPages { get; set; }

        /// <summary>
        /// An array of request-related [HATEOAS links](/api/rest/responses/#hateoas-links).
        /// </summary>
        [JsonProperty("links", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.LinkDescription> Links { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"SearchResponse : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is SearchResponse other &&
                (this.TransactionDetails == null && other.TransactionDetails == null ||
                 this.TransactionDetails?.Equals(other.TransactionDetails) == true) &&
                (this.AccountNumber == null && other.AccountNumber == null ||
                 this.AccountNumber?.Equals(other.AccountNumber) == true) &&
                (this.StartDate == null && other.StartDate == null ||
                 this.StartDate?.Equals(other.StartDate) == true) &&
                (this.EndDate == null && other.EndDate == null ||
                 this.EndDate?.Equals(other.EndDate) == true) &&
                (this.LastRefreshedDatetime == null && other.LastRefreshedDatetime == null ||
                 this.LastRefreshedDatetime?.Equals(other.LastRefreshedDatetime) == true) &&
                (this.Page == null && other.Page == null ||
                 this.Page?.Equals(other.Page) == true) &&
                (this.TotalItems == null && other.TotalItems == null ||
                 this.TotalItems?.Equals(other.TotalItems) == true) &&
                (this.TotalPages == null && other.TotalPages == null ||
                 this.TotalPages?.Equals(other.TotalPages) == true) &&
                (this.Links == null && other.Links == null ||
                 this.Links?.Equals(other.Links) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"TransactionDetails = {(this.TransactionDetails == null ? "null" : $"[{string.Join(", ", this.TransactionDetails)} ]")}");
            toStringOutput.Add($"AccountNumber = {this.AccountNumber ?? "null"}");
            toStringOutput.Add($"StartDate = {this.StartDate ?? "null"}");
            toStringOutput.Add($"EndDate = {this.EndDate ?? "null"}");
            toStringOutput.Add($"LastRefreshedDatetime = {this.LastRefreshedDatetime ?? "null"}");
            toStringOutput.Add($"Page = {(this.Page == null ? "null" : this.Page.ToString())}");
            toStringOutput.Add($"TotalItems = {(this.TotalItems == null ? "null" : this.TotalItems.ToString())}");
            toStringOutput.Add($"TotalPages = {(this.TotalPages == null ? "null" : this.TotalPages.ToString())}");
            toStringOutput.Add($"Links = {(this.Links == null ? "null" : $"[{string.Join(", ", this.Links)} ]")}");
        }
    }
}