// <copyright file="SepaDebitRequest.cs" company="APIMatic">
// PaypalServerSdk.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace PaypalServerSdk.Standard.Models
{
    /// <summary>
    /// SepaDebitRequest.
    /// </summary>
    public class SepaDebitRequest
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SepaDebitRequest"/> class.
        /// </summary>
        public SepaDebitRequest()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SepaDebitRequest"/> class.
        /// </summary>
        /// <param name="experienceContext">experience_context.</param>
        public SepaDebitRequest(
            Models.SepaDebitExperienceContext experienceContext = null)
        {
            this.ExperienceContext = experienceContext;
        }

        /// <summary>
        /// Customizes the payer experience during the approval process for the SEPA Debit payment.
        /// </summary>
        [JsonProperty("experience_context", NullValueHandling = NullValueHandling.Ignore)]
        public Models.SepaDebitExperienceContext ExperienceContext { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"SepaDebitRequest : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is SepaDebitRequest other &&
                (this.ExperienceContext == null && other.ExperienceContext == null ||
                 this.ExperienceContext?.Equals(other.ExperienceContext) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"ExperienceContext = {(this.ExperienceContext == null ? "null" : this.ExperienceContext.ToString())}");
        }
    }
}