// <copyright file="SetupFeeFailureAction.cs" company="APIMatic">
// PaypalServerSdk.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace PaypalServerSdk.Standard.Models
{
    /// <summary>
    /// SetupFeeFailureAction.
    /// </summary>

    [JsonConverter(typeof(UnknownEnumConverter<StringEnumConverter>), nameof(_Unknown))]
    public enum SetupFeeFailureAction
    {
        /// <summary>
        ///Continues the subscription if the initial payment for the setup fails.
        /// Continue.
        /// </summary>
        [EnumMember(Value = "CONTINUE")]
        Continue,

        /// <summary>
        ///Cancels the subscription if the initial payment for the setup fails.
        /// Cancel.
        /// </summary>
        [EnumMember(Value = "CANCEL")]
        Cancel,

        /// <summary>
        /// Unknown values will be mapped by this enum member.
        /// </summary>
        _Unknown
    }
}