// <copyright file="ShippingInformation.cs" company="APIMatic">
// PaypalServerSdk.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using PaypalServerSdk.Standard;
using PaypalServerSdk.Standard.Utilities;

namespace PaypalServerSdk.Standard.Models
{
    /// <summary>
    /// ShippingInformation.
    /// </summary>
    public class ShippingInformation
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ShippingInformation"/> class.
        /// </summary>
        public ShippingInformation()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ShippingInformation"/> class.
        /// </summary>
        /// <param name="name">name.</param>
        /// <param name="method">method.</param>
        /// <param name="address">address.</param>
        /// <param name="secondaryShippingAddress">secondary_shipping_address.</param>
        public ShippingInformation(
            string name = null,
            string method = null,
            Models.SimplePostalAddressCoarseGrained address = null,
            Models.SimplePostalAddressCoarseGrained secondaryShippingAddress = null)
        {
            this.Name = name;
            this.Method = method;
            this.Address = address;
            this.SecondaryShippingAddress = secondaryShippingAddress;
        }

        /// <summary>
        /// The recipient's name.
        /// </summary>
        [JsonProperty("name", NullValueHandling = NullValueHandling.Ignore)]
        public string Name { get; set; }

        /// <summary>
        /// The shipping method that is associated with this order.
        /// </summary>
        [JsonProperty("method", NullValueHandling = NullValueHandling.Ignore)]
        public string Method { get; set; }

        /// <summary>
        /// A simple postal address with coarse-grained fields. Do not use for an international address. Use for backward compatibility only. Does not contain phone.
        /// </summary>
        [JsonProperty("address", NullValueHandling = NullValueHandling.Ignore)]
        public Models.SimplePostalAddressCoarseGrained Address { get; set; }

        /// <summary>
        /// A simple postal address with coarse-grained fields. Do not use for an international address. Use for backward compatibility only. Does not contain phone.
        /// </summary>
        [JsonProperty("secondary_shipping_address", NullValueHandling = NullValueHandling.Ignore)]
        public Models.SimplePostalAddressCoarseGrained SecondaryShippingAddress { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ShippingInformation : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is ShippingInformation other &&
                (this.Name == null && other.Name == null ||
                 this.Name?.Equals(other.Name) == true) &&
                (this.Method == null && other.Method == null ||
                 this.Method?.Equals(other.Method) == true) &&
                (this.Address == null && other.Address == null ||
                 this.Address?.Equals(other.Address) == true) &&
                (this.SecondaryShippingAddress == null && other.SecondaryShippingAddress == null ||
                 this.SecondaryShippingAddress?.Equals(other.SecondaryShippingAddress) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Name = {this.Name ?? "null"}");
            toStringOutput.Add($"Method = {this.Method ?? "null"}");
            toStringOutput.Add($"Address = {(this.Address == null ? "null" : this.Address.ToString())}");
            toStringOutput.Add($"SecondaryShippingAddress = {(this.SecondaryShippingAddress == null ? "null" : this.SecondaryShippingAddress.ToString())}");
        }
    }
}