// <copyright file="ShippingName.cs" company="APIMatic">
// PaypalServerSdk.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace PaypalServerSdk.Standard.Models
{
    /// <summary>
    /// ShippingName.
    /// </summary>
    public class ShippingName
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ShippingName"/> class.
        /// </summary>
        public ShippingName()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ShippingName"/> class.
        /// </summary>
        /// <param name="fullName">full_name.</param>
        public ShippingName(
            string fullName = null)
        {
            this.FullName = fullName;
        }

        /// <summary>
        /// When the party is a person, the party's full name.
        /// </summary>
        [JsonProperty("full_name", NullValueHandling = NullValueHandling.Ignore)]
        public string FullName { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ShippingName : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is ShippingName other &&
                (this.FullName == null && other.FullName == null ||
                 this.FullName?.Equals(other.FullName) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"FullName = {this.FullName ?? "null"}");
        }
    }
}