// <copyright file="StoreInVaultInstruction.cs" company="APIMatic">
// PaypalServerSdk.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace PaypalServerSdk.Standard.Models
{
    /// <summary>
    /// StoreInVaultInstruction.
    /// </summary>

    [JsonConverter(typeof(UnknownEnumConverter<StringEnumConverter>), nameof(_Unknown))]
    public enum StoreInVaultInstruction
    {
        /// <summary>
        ///Defines that the payment_source will be vaulted only when at least one authorization or capture using that payment_source is successful.
        /// OnSuccess.
        /// </summary>
        [EnumMember(Value = "ON_SUCCESS")]
        OnSuccess,

        /// <summary>
        /// Unknown values will be mapped by this enum member.
        /// </summary>
        _Unknown
    }
}