// <copyright file="SubscriptionPayerName.cs" company="APIMatic">
// PaypalServerSdk.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace PaypalServerSdk.Standard.Models
{
    /// <summary>
    /// SubscriptionPayerName.
    /// </summary>
    public class SubscriptionPayerName
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SubscriptionPayerName"/> class.
        /// </summary>
        public SubscriptionPayerName()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SubscriptionPayerName"/> class.
        /// </summary>
        /// <param name="prefix">prefix.</param>
        /// <param name="givenName">given_name.</param>
        /// <param name="surname">surname.</param>
        /// <param name="middleName">middle_name.</param>
        /// <param name="suffix">suffix.</param>
        /// <param name="fullName">full_name.</param>
        public SubscriptionPayerName(
            string prefix = null,
            string givenName = null,
            string surname = null,
            string middleName = null,
            string suffix = null,
            string fullName = null)
        {
            this.Prefix = prefix;
            this.GivenName = givenName;
            this.Surname = surname;
            this.MiddleName = middleName;
            this.Suffix = suffix;
            this.FullName = fullName;
        }

        /// <summary>
        /// The prefix, or title, to the party's name.
        /// </summary>
        [JsonProperty("prefix", NullValueHandling = NullValueHandling.Ignore)]
        public string Prefix { get; set; }

        /// <summary>
        /// When the party is a person, the party's given, or first, name.
        /// </summary>
        [JsonProperty("given_name", NullValueHandling = NullValueHandling.Ignore)]
        public string GivenName { get; set; }

        /// <summary>
        /// When the party is a person, the party's surname or family name. Also known as the last name. Required when the party is a person. Use also to store multiple surnames including the matronymic, or mother's, surname.
        /// </summary>
        [JsonProperty("surname", NullValueHandling = NullValueHandling.Ignore)]
        public string Surname { get; set; }

        /// <summary>
        /// When the party is a person, the party's middle name. Use also to store multiple middle names including the patronymic, or father's, middle name.
        /// </summary>
        [JsonProperty("middle_name", NullValueHandling = NullValueHandling.Ignore)]
        public string MiddleName { get; set; }

        /// <summary>
        /// The suffix for the party's name.
        /// </summary>
        [JsonProperty("suffix", NullValueHandling = NullValueHandling.Ignore)]
        public string Suffix { get; set; }

        /// <summary>
        /// When the party is a person, the party's full name.
        /// </summary>
        [JsonProperty("full_name", NullValueHandling = NullValueHandling.Ignore)]
        public string FullName { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"SubscriptionPayerName : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is SubscriptionPayerName other &&
                (this.Prefix == null && other.Prefix == null ||
                 this.Prefix?.Equals(other.Prefix) == true) &&
                (this.GivenName == null && other.GivenName == null ||
                 this.GivenName?.Equals(other.GivenName) == true) &&
                (this.Surname == null && other.Surname == null ||
                 this.Surname?.Equals(other.Surname) == true) &&
                (this.MiddleName == null && other.MiddleName == null ||
                 this.MiddleName?.Equals(other.MiddleName) == true) &&
                (this.Suffix == null && other.Suffix == null ||
                 this.Suffix?.Equals(other.Suffix) == true) &&
                (this.FullName == null && other.FullName == null ||
                 this.FullName?.Equals(other.FullName) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Prefix = {this.Prefix ?? "null"}");
            toStringOutput.Add($"GivenName = {this.GivenName ?? "null"}");
            toStringOutput.Add($"Surname = {this.Surname ?? "null"}");
            toStringOutput.Add($"MiddleName = {this.MiddleName ?? "null"}");
            toStringOutput.Add($"Suffix = {this.Suffix ?? "null"}");
            toStringOutput.Add($"FullName = {this.FullName ?? "null"}");
        }
    }
}