// <copyright file="SubscriptionTransactionDetails.cs" company="APIMatic">
// PaypalServerSdk.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using PaypalServerSdk.Standard;
using PaypalServerSdk.Standard.Utilities;

namespace PaypalServerSdk.Standard.Models
{
    /// <summary>
    /// SubscriptionTransactionDetails.
    /// </summary>
    public class SubscriptionTransactionDetails
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SubscriptionTransactionDetails"/> class.
        /// </summary>
        public SubscriptionTransactionDetails()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SubscriptionTransactionDetails"/> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="amountWithBreakdown">amount_with_breakdown.</param>
        /// <param name="time">time.</param>
        /// <param name="status">status.</param>
        /// <param name="payerName">payer_name.</param>
        /// <param name="payerEmail">payer_email.</param>
        public SubscriptionTransactionDetails(
            string id,
            Models.SubscriptionAmountWithBreakdown amountWithBreakdown,
            string time,
            Models.CaptureStatus? status = null,
            Models.SubscriptionPayerName payerName = null,
            string payerEmail = null)
        {
            this.Status = status;
            this.Id = id;
            this.AmountWithBreakdown = amountWithBreakdown;
            this.PayerName = payerName;
            this.PayerEmail = payerEmail;
            this.Time = time;
        }

        /// <summary>
        /// The status of the captured payment.
        /// </summary>
        [JsonProperty("status", NullValueHandling = NullValueHandling.Ignore)]
        public Models.CaptureStatus? Status { get; set; }

        /// <summary>
        /// The PayPal-generated transaction ID.
        /// </summary>
        [JsonProperty("id")]
        public string Id { get; set; }

        /// <summary>
        /// The breakdown details for the amount. Includes the gross, tax, fee, and shipping amounts.
        /// </summary>
        [JsonProperty("amount_with_breakdown")]
        public Models.SubscriptionAmountWithBreakdown AmountWithBreakdown { get; set; }

        /// <summary>
        /// The name of the party.
        /// </summary>
        [JsonProperty("payer_name", NullValueHandling = NullValueHandling.Ignore)]
        public Models.SubscriptionPayerName PayerName { get; set; }

        /// <summary>
        /// The internationalized email address. Note: Up to 64 characters are allowed before and 255 characters are allowed after the @ sign. However, the generally accepted maximum length for an email address is 254 characters. The pattern verifies that an unquoted @ sign exists.
        /// </summary>
        [JsonProperty("payer_email", NullValueHandling = NullValueHandling.Ignore)]
        public string PayerEmail { get; set; }

        /// <summary>
        /// The date and time, in [Internet date and time format](https://tools.ietf.org/html/rfc3339#section-5.6). Seconds are required while fractional seconds are optional. Note: The regular expression provides guidance but does not reject all invalid dates.
        /// </summary>
        [JsonProperty("time")]
        public string Time { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"SubscriptionTransactionDetails : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is SubscriptionTransactionDetails other &&
                (this.Status == null && other.Status == null ||
                 this.Status?.Equals(other.Status) == true) &&
                (this.Id == null && other.Id == null ||
                 this.Id?.Equals(other.Id) == true) &&
                (this.AmountWithBreakdown == null && other.AmountWithBreakdown == null ||
                 this.AmountWithBreakdown?.Equals(other.AmountWithBreakdown) == true) &&
                (this.PayerName == null && other.PayerName == null ||
                 this.PayerName?.Equals(other.PayerName) == true) &&
                (this.PayerEmail == null && other.PayerEmail == null ||
                 this.PayerEmail?.Equals(other.PayerEmail) == true) &&
                (this.Time == null && other.Time == null ||
                 this.Time?.Equals(other.Time) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Status = {(this.Status == null ? "null" : this.Status.ToString())}");
            toStringOutput.Add($"Id = {this.Id ?? "null"}");
            toStringOutput.Add($"AmountWithBreakdown = {(this.AmountWithBreakdown == null ? "null" : this.AmountWithBreakdown.ToString())}");
            toStringOutput.Add($"PayerName = {(this.PayerName == null ? "null" : this.PayerName.ToString())}");
            toStringOutput.Add($"PayerEmail = {this.PayerEmail ?? "null"}");
            toStringOutput.Add($"Time = {this.Time ?? "null"}");
        }
    }
}