// <copyright file="Taxes.cs" company="APIMatic">
// PaypalServerSdk.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace PaypalServerSdk.Standard.Models
{
    /// <summary>
    /// Taxes.
    /// </summary>
    public class Taxes
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Taxes"/> class.
        /// </summary>
        public Taxes()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Taxes"/> class.
        /// </summary>
        /// <param name="percentage">percentage.</param>
        /// <param name="inclusive">inclusive.</param>
        public Taxes(
            string percentage,
            bool? inclusive = true)
        {
            this.Percentage = percentage;
            this.Inclusive = inclusive;
        }

        /// <summary>
        /// The percentage, as a fixed-point, signed decimal number. For example, define a 19.99% interest rate as `19.99`.
        /// </summary>
        [JsonProperty("percentage")]
        public string Percentage { get; set; }

        /// <summary>
        /// Indicates whether the tax was already included in the billing amount.
        /// </summary>
        [JsonProperty("inclusive", NullValueHandling = NullValueHandling.Ignore)]
        public bool? Inclusive { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"Taxes : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is Taxes other &&
                (this.Percentage == null && other.Percentage == null ||
                 this.Percentage?.Equals(other.Percentage) == true) &&
                (this.Inclusive == null && other.Inclusive == null ||
                 this.Inclusive?.Equals(other.Inclusive) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Percentage = {this.Percentage ?? "null"}");
            toStringOutput.Add($"Inclusive = {(this.Inclusive == null ? "null" : this.Inclusive.ToString())}");
        }
    }
}