// <copyright file="TransactionsList.cs" company="APIMatic">
// PaypalServerSdk.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using PaypalServerSdk.Standard;
using PaypalServerSdk.Standard.Utilities;

namespace PaypalServerSdk.Standard.Models
{
    /// <summary>
    /// TransactionsList.
    /// </summary>
    public class TransactionsList
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TransactionsList"/> class.
        /// </summary>
        public TransactionsList()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TransactionsList"/> class.
        /// </summary>
        /// <param name="transactions">transactions.</param>
        /// <param name="totalItems">total_items.</param>
        /// <param name="totalPages">total_pages.</param>
        /// <param name="links">links.</param>
        public TransactionsList(
            List<Models.SubscriptionTransactionDetails> transactions = null,
            int? totalItems = null,
            int? totalPages = null,
            List<Models.LinkDescription> links = null)
        {
            this.Transactions = transactions;
            this.TotalItems = totalItems;
            this.TotalPages = totalPages;
            this.Links = links;
        }

        /// <summary>
        /// An array of transactions.
        /// </summary>
        [JsonProperty("transactions", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.SubscriptionTransactionDetails> Transactions { get; set; }

        /// <summary>
        /// The total number of items.
        /// </summary>
        [JsonProperty("total_items", NullValueHandling = NullValueHandling.Ignore)]
        public int? TotalItems { get; set; }

        /// <summary>
        /// The total number of pages.
        /// </summary>
        [JsonProperty("total_pages", NullValueHandling = NullValueHandling.Ignore)]
        public int? TotalPages { get; set; }

        /// <summary>
        /// An array of request-related [HATEOAS links](/docs/api/reference/api-responses/#hateoas-links).
        /// </summary>
        [JsonProperty("links", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.LinkDescription> Links { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"TransactionsList : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is TransactionsList other &&
                (this.Transactions == null && other.Transactions == null ||
                 this.Transactions?.Equals(other.Transactions) == true) &&
                (this.TotalItems == null && other.TotalItems == null ||
                 this.TotalItems?.Equals(other.TotalItems) == true) &&
                (this.TotalPages == null && other.TotalPages == null ||
                 this.TotalPages?.Equals(other.TotalPages) == true) &&
                (this.Links == null && other.Links == null ||
                 this.Links?.Equals(other.Links) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Transactions = {(this.Transactions == null ? "null" : $"[{string.Join(", ", this.Transactions)} ]")}");
            toStringOutput.Add($"TotalItems = {(this.TotalItems == null ? "null" : this.TotalItems.ToString())}");
            toStringOutput.Add($"TotalPages = {(this.TotalPages == null ? "null" : this.TotalPages.ToString())}");
            toStringOutput.Add($"Links = {(this.Links == null ? "null" : $"[{string.Join(", ", this.Links)} ]")}");
        }
    }
}