// <copyright file="UpdatePricingSchemesRequest.cs" company="APIMatic">
// PaypalServerSdk.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace PaypalServerSdk.Standard.Models
{
    /// <summary>
    /// UpdatePricingSchemesRequest.
    /// </summary>
    public class UpdatePricingSchemesRequest
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdatePricingSchemesRequest"/> class.
        /// </summary>
        public UpdatePricingSchemesRequest()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UpdatePricingSchemesRequest"/> class.
        /// </summary>
        /// <param name="pricingSchemes">pricing_schemes.</param>
        public UpdatePricingSchemesRequest(
            List<Models.UpdatePricingScheme> pricingSchemes)
        {
            this.PricingSchemes = pricingSchemes;
        }

        /// <summary>
        /// An array of pricing schemes.
        /// </summary>
        [JsonProperty("pricing_schemes")]
        public List<Models.UpdatePricingScheme> PricingSchemes { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"UpdatePricingSchemesRequest : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is UpdatePricingSchemesRequest other &&
                (this.PricingSchemes == null && other.PricingSchemes == null ||
                 this.PricingSchemes?.Equals(other.PricingSchemes) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"PricingSchemes = {(this.PricingSchemes == null ? "null" : $"[{string.Join(", ", this.PricingSchemes)} ]")}");
        }
    }
}