// <copyright file="VaultResponseCustomer.cs" company="APIMatic">
// Copyright (c) APIMatic. All rights reserved.
// </copyright>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using PaypalServerSdk.Standard;
using PaypalServerSdk.Standard.Utilities;

namespace PaypalServerSdk.Standard.Models
{
    /// <summary>
    /// VaultResponseCustomer.
    /// </summary>
    public class VaultResponseCustomer
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VaultResponseCustomer"/> class.
        /// </summary>
        public VaultResponseCustomer()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="VaultResponseCustomer"/> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="merchantCustomerId">merchant_customer_id.</param>
        /// <param name="links">links.</param>
        public VaultResponseCustomer(
            string id = null,
            string merchantCustomerId = null,
            List<JsonValue> links = null)
        {
            this.Id = id;
            this.MerchantCustomerId = merchantCustomerId;
            this.Links = links;
        }

        /// <summary>
        /// The unique ID for a customer generated by PayPal.
        /// </summary>
        [JsonProperty("id", NullValueHandling = NullValueHandling.Ignore)]
        public string Id { get; set; }

        /// <summary>
        /// Merchants and partners may already have a data-store where their customer information is persisted. Use merchant_customer_id to associate the PayPal-generated customer.id to your representation of a customer.
        /// </summary>
        [JsonProperty("merchant_customer_id", NullValueHandling = NullValueHandling.Ignore)]
        public string MerchantCustomerId { get; set; }

        /// <summary>
        /// DEPRECATED. This field is DEPRECATED.
        /// </summary>
        [JsonProperty("links", NullValueHandling = NullValueHandling.Ignore)]
        public List<JsonValue> Links { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"VaultResponseCustomer : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is VaultResponseCustomer other &&
                (this.Id == null && other.Id == null ||
                 this.Id?.Equals(other.Id) == true) &&
                (this.MerchantCustomerId == null && other.MerchantCustomerId == null ||
                 this.MerchantCustomerId?.Equals(other.MerchantCustomerId) == true) &&
                (this.Links == null && other.Links == null ||
                 this.Links?.Equals(other.Links) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Id = {this.Id ?? "null"}");
            toStringOutput.Add($"MerchantCustomerId = {this.MerchantCustomerId ?? "null"}");
            toStringOutput.Add($"Links = {(this.Links == null ? "null" : this.Links.ToString())}");
        }
    }
}