// <copyright file="VenmoExperienceContext.cs" company="APIMatic">
// PaypalServerSdk.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using PaypalServerSdk.Standard;
using PaypalServerSdk.Standard.Utilities;

namespace PaypalServerSdk.Standard.Models
{
    /// <summary>
    /// VenmoExperienceContext.
    /// </summary>
    public class VenmoExperienceContext
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VenmoExperienceContext"/> class.
        /// </summary>
        public VenmoExperienceContext()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="VenmoExperienceContext"/> class.
        /// </summary>
        /// <param name="brandName">brand_name.</param>
        /// <param name="shippingPreference">shipping_preference.</param>
        /// <param name="vaultInstruction">vault_instruction.</param>
        /// <param name="userAction">user_action.</param>
        public VenmoExperienceContext(
            string brandName = null,
            Models.ExperienceContextShippingPreference? shippingPreference = Models.ExperienceContextShippingPreference.GetFromFile,
            Models.VaultInstructionAction? vaultInstruction = null,
            Models.VaultUserAction? userAction = Models.VaultUserAction.Continue)
        {
            this.BrandName = brandName;
            this.ShippingPreference = shippingPreference;
            this.VaultInstruction = vaultInstruction;
            this.UserAction = userAction;
        }

        /// <summary>
        /// The label that overrides the business name in the PayPal account on the PayPal site. The pattern is defined by an external party and supports Unicode.
        /// </summary>
        [JsonProperty("brand_name", NullValueHandling = NullValueHandling.Ignore)]
        public string BrandName { get; set; }

        /// <summary>
        /// The shipping preference. This only applies to PayPal payment source.
        /// </summary>
        [JsonProperty("shipping_preference", NullValueHandling = NullValueHandling.Ignore)]
        public Models.ExperienceContextShippingPreference? ShippingPreference { get; set; }

        /// <summary>
        /// DEPRECATED. Vault Instruction on action to be performed after a successful payer approval.
        /// </summary>
        [JsonProperty("vault_instruction", NullValueHandling = NullValueHandling.Ignore)]
        public Models.VaultInstructionAction? VaultInstruction { get; set; }

        /// <summary>
        /// User Action on action to be performed after a successful payer approval.
        /// </summary>
        [JsonProperty("user_action", NullValueHandling = NullValueHandling.Ignore)]
        public Models.VaultUserAction? UserAction { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"VenmoExperienceContext : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is VenmoExperienceContext other &&
                (this.BrandName == null && other.BrandName == null ||
                 this.BrandName?.Equals(other.BrandName) == true) &&
                (this.ShippingPreference == null && other.ShippingPreference == null ||
                 this.ShippingPreference?.Equals(other.ShippingPreference) == true) &&
                (this.VaultInstruction == null && other.VaultInstruction == null ||
                 this.VaultInstruction?.Equals(other.VaultInstruction) == true) &&
                (this.UserAction == null && other.UserAction == null ||
                 this.UserAction?.Equals(other.UserAction) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"BrandName = {this.BrandName ?? "null"}");
            toStringOutput.Add($"ShippingPreference = {(this.ShippingPreference == null ? "null" : this.ShippingPreference.ToString())}");
            toStringOutput.Add($"VaultInstruction = {(this.VaultInstruction == null ? "null" : this.VaultInstruction.ToString())}");
            toStringOutput.Add($"UserAction = {(this.UserAction == null ? "null" : this.UserAction.ToString())}");
        }
    }
}