name: Unit Tests
env:
  PAYPAL_SERVER_SDK_STANDARD_ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
  PAYPAL_SERVER_SDK_STANDARD_O_AUTH_CLIENT_ID: ${{ secrets.CLIENT_ID }}
  PAYPAL_SERVER_SDK_STANDARD_O_AUTH_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
  EMAIL: ${{ secrets.EMAIL }}
  PASSWORD: ${{ secrets.PASSWORD }}
on:
  workflow_dispatch:
jobs:
  unit-tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x
    - name: Add testing projects to solution
      run: |
        dotnet sln PaypalServerSDK.sln add e2eTests/e2eTests.csproj
        dotnet sln PaypalServerSDK.sln add unitTests/unitTests.csproj
    - name: Make internals visible to tests
      run: |
        sed -i '/<\/Project>/i \
        <ItemGroup>\n\
          <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">\n\
            <_Parameter1>unitTests</_Parameter1>\n\
          </AssemblyAttribute>\n\
          <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">\n\
            <_Parameter1>e2eTests</_Parameter1>\n\
          </AssemblyAttribute>\n\
        </ItemGroup>' PaypalServerSdk.Standard/PaypalServerSDK.Standard.csproj
    - run: dotnet build
    - name: Run your tests
      run: dotnet test unitTests
